version: '3.6'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  filebeat:
    container_name: filebeat
    hostname: filebeat
    user: root
    image: docker.elastic.co/beats/filebeat:7.4.0
    volumes:
      #Mount the filebeat configuration so users can make edit
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      #Mount the mysql logs into the filebeat container so we can access and and index them using the filebeat mysql module
      - ./db/logs:/var/log/mysql/
      #Named volume fsdata. This is used to persist the registry file between restarts, so to avoid data duplication
      - fbdata:/usr/share/filebeat/data/
    command: filebeat -strict.perms=false
    restart: on-failure
#
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3306:3306
    volumes:
      - "./db/mysql.conf.d:/etc/mysql/conf.d"
      - "./db/data:/var/lib/mysql:rw"
      - "./db/logs:/var/log/mysql/"

  mongo:
    container_name: mongo
    image: "mongo:5.0"
    volumes:
      - ./db/mongo_data:/data/db
    ports:
      - 27017:27017

  graylog:
    container_name: graylog
    image: graylog/graylog:5.0
    volumes:
      - "./graylog/graylog_journal:/usr/share/graylog/data/journal"
    environment:
      - GRAYLOG_PASSWORD_SECRET=zlIHRdgRQCdI6IO0CARTlpaEcaOHQEzFLG2gZI6oPMLqQkL2Uy7BheJXohibot5hIABZx5WqcQK690g61UrYK00G6VHLaZJP
      - GRAYLOG_ROOT_PASSWORD_SHA2=f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    depends_on:
      - mongo
      - elasticsearch
    restart: always
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp



volumes:
  fbdata:


